#! /bin/sh
### BEGIN INIT INFO
# Provides: seba
# Required-Start: $docker $remote_fs $syslog
# Required-Stop: $docker $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: SEBA Performance Testing
# Description: This file starts and stops SEBA single-node
# 
### END INIT INFO

SEBA_DIR=/home/seba/

case "$1" in
  start)
   su seba -c $SEBA_DIR/seba_start.sh
   ;;
  stop)
   su seba -c $SEBA_DIR/seba_stop.sh
   sleep 10
   ;;
  restart)
   su seba -c $SEBA_DIR/seba_stop.sh
   sleep 20
   su seba -c $SEBA_DIR/seba_start.sh
   ;;
*)

   echo "Usage: voltha {start|stop|restart}" >&2
   exit 3
   ;;
esac
