#! /bin/sh
### BEGIN INIT INFO
# Provides: onu_mock
# Required-Start: $docker $remote_fs $syslog
# Required-Stop: $docker $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ONU Mock
# Description: This file starts and stops ONU Mock app
# 
### END INIT INFO

ONU_MOCK_DIR=/home/admin/

case "$1" in
  start)
   su adminit -c ONU_MOCK_DIR/voltha_start.sh
   ;;
  stop)
   su adminit -c ONU_MOCK_DIR/voltha_stop.sh
   sleep 10
   ;;
  restart)
   su adminit -c ONU_MOCK_DIR/voltha_stop.sh
   sleep 20
   su adminit -c ONU_MOCK_DIR/voltha_start.sh
   ;;
*)

   echo "Usage: onu_mock {start|stop|restart}" >&2
   exit 3
   ;;
esac
