#! /bin/sh
### BEGIN INIT INFO
# Provides: voltha
# Required-Start: $docker $remote_fs $syslog
# Required-Stop: $docker $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: VOLTHA Performance Testing
# Description: This file starts and stops VOLTHA single-node
# 
### END INIT INFO

VOLTHA_DIR=/home/voltha/

case "$1" in
  start)
   su voltha -c $VOLTHA_DIR/voltha_start.sh
   ;;
  stop)
   su voltha -c $VOLTHA_DIR/voltha_stop.sh
   sleep 10
   ;;
  restart)
   su voltha -c $VOLTHA_DIR/voltha_stop.sh
   sleep 20
   su voltha -c $VOLTHA_DIR/voltha_start.sh
   ;;
*)

   echo "Usage: voltha {start|stop|restart}" >&2
   exit 3
   ;;
esac
