#! /bin/sh
### BEGIN INIT INFO
# Provides: voltha
# Required-Start: $docker $remote_fs $syslog
# Required-Stop: $docker $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: VOLTHA Performance Testing
# Description: This file starts and stops VOLTHA single-node
# 
### END INIT INFO

set -e

BASE=voltha
VOLTHA_DIR=/home/$BASE
VOLTHA_LOG=/var/log/$BASE.log

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$VOLTHA_DIR

touch "$VOLTHA_LOG"

# Get lsb functions
. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
   . /etc/default/$BASE
fi

case "$1" in
  start)
   log_begin_msg "Starting VOLTHA: $VOLTHA_DIR" >$VOLTHA_LOG 2>&1
   su voltha -c $VOLTHA_DIR/voltha_start.sh
   ;;

  stop)
   log_begin_msg "Stopping VOLTHA" >$VOLTHA_LOG 2>&1
   su voltha -c $VOLTHA_DIR/voltha_stop.sh
   ;;

  restart)
   su voltha -c $VOLTHA_DIR/voltha_stop.sh
   sleep 10
   su voltha -c $VOLTHA_DIR/voltha_start.sh
   ;;

  *)
   echo "Usage: voltha {start|stop|restart}" >&2
   exit 3
   ;;
esac
